# Generated by Django 3.0.3 on 2020-06-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripción', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EQUIPOSCOLOSO',
            fields=[
                ('Codigo_e', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_equipo', models.CharField(max_length=500)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Tipo_equipo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EquiposPuertoColoso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bomba_funcionando', models.IntegerField()),
                ('presion_agua_sello', models.IntegerField()),
                ('flujo_agua_sello', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('flujo_transmisor', models.IntegerField()),
                ('densimetro_nuclear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FALLAS',
            fields=[
                ('Codigo_f', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_falla', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesBuscadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SENSORES',
            fields=[
                ('Fecha', models.DateTimeField(blank=True, default=None, primary_key=True, serialize=False)),
                ('Presion_agua_sello', models.FloatField()),
                ('Flujo_agua_sello', models.FloatField()),
                ('Velocidad', models.FloatField()),
                ('Flujo_transmisor', models.FloatField()),
                ('Densimetro_nuclear', models.FloatField()),
                ('Temperatura', models.FloatField()),
                ('Aceleracion', models.FloatField()),
                ('Velocidad_vibracion', models.FloatField()),
                ('Ingreso', models.CharField(max_length=10)),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predecirFotos.EQUIPOSCOLOSO')),
            ],
        ),
        migrations.CreateModel(
            name='SENSORESFALLAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porc_falla', models.FloatField()),
                ('Fallas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predecirFotos.FALLAS')),
                ('Sensores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predecirFotos.SENSORES')),
            ],
        ),
        migrations.CreateModel(
            name='Sensores_excel',
            fields=[
                ('Fecha', models.DateTimeField(blank=True, default=None, primary_key=True, serialize=False)),
                ('Funcionando', models.IntegerField()),
                ('Presion_agua_sello', models.FloatField()),
                ('Flujo_agua_sello', models.FloatField()),
                ('Velocidad', models.FloatField()),
                ('Flujo_transmisor', models.FloatField()),
                ('Densimetro_nuclear', models.FloatField()),
                ('Temperatura', models.FloatField()),
                ('Aceleracion', models.FloatField()),
                ('Velocidad_vibracion', models.FloatField()),
                ('Equipo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predecirFotos.EQUIPOSCOLOSO')),
            ],
        ),
        migrations.AddField(
            model_name='sensores',
            name='Falla',
            field=models.ManyToManyField(through='predecirFotos.SENSORESFALLAS', to='predecirFotos.FALLAS'),
        ),
    ]
